### ISSUE TITLE
versatility of csw-services.sh, and multiple users

### ISSUE THREAD

**Issue by edwardchapin** [tmtsoftware/csw-prototype#3]
In a multi-user environment it is not possible to use csw-services.sh as it assumes the same directories, in particular:
```
/tmp/csw # for service lock and log files
/tmp/CsTestOversize
/tmp/CsTestMainRepo
```
Some suggestions:
* Have the possibility to have a single, system-wide Redis instance running that multiple instances of the various services could share.
* Barring the above, allow for multiple instances of Redis running on different, configurable ports for each user.
* Use different directories in `/tmp` for all of the ephemeral service and test data (e.g., partition by username).
* If a single top-level directory is used for all users, e.g., `/tmp/csw`, ensure that it has **+rwx** permissions when it is initially created.

In addition, there is a small change that may help new users trying to run tests. If `CSW_INSTALL` is incorrectly set, but points to an existing directory, csw-services.sh will fail silently. It would be helpful to add tests for the existence of `$CSW_INSTALL/bin/[all service executables]` and then exit with bad status and display a message to the user.

**Comment by abrighton** [comment]
I checked in changes to the csw master branch that should fix these issues. Now Redis is started on a random free port and registered with the location service. Note that the firewall needs to be off or the applications will not be able to connect.

You can now optionally define the environment variable `CSW_SERVICE_PREFIX` if you are testing in a network where other instances may also be running. This will make all the directories and location service names unique. 
You can also define it as a system property (for example, by passing `-DCSW_SERVICE_PREFIX=myname` to every application), however this seems less practical.

I changed the default config files for the config service to include `$CSW_SERVICE_PREFIX` in the path name to the repository, if defined. The repositories are currently set to be under `/tmp`. In a production environment, they would need to be set to some permanent directory.

I also updated the `csw-services.sh` script to check that all required files under install are available.
